kind = "web"
previewPath = "/"
title = "For Shiyaa"
version = "1.0.0"
id = "artifacts/for-shiyaa"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24535

[services.development]
run = "pnpm --filter @workspace/for-shiyaa run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/for-shiyaa", "run", "build" ]
publicDir = "artifacts/for-shiyaa/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24535"
BASE_PATH = "/"
